<?php
/**
 * Extendable functions and definitions
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 *
 * @package Extendable
 * @since Extendable 1.0
 */


if ( ! defined( 'EXTENDABLE_THEME_VERSION' ) ) {
	$theme_version = wp_get_theme()->get( 'Version' );
	define( 'EXTENDABLE_THEME_VERSION', is_string( $theme_version ) ? $theme_version : '1.0.0' );
}

if ( ! function_exists( 'extendable_support' ) ) :

	/**
	 * Sets up theme defaults and registers support for various WordPress features.
	 *
	 * @since Extendable 1.0
	 *
	 * @return void
	 */
	function extendable_support() {

		// Add support for block styles.
		add_theme_support( 'wp-block-styles' );

		global $wp_version;
		// Add style for WordPress older versions.
		if ( version_compare( $wp_version, '6.0.2', '<=' ) ) {
			$editor_style = array(
				'style.css',
				'/assets/css/deprecate-style.css',
			);
		} else {
			$editor_style = 'style.css';
		}
		// Enqueue editor styles.
		add_editor_style( $editor_style );
	}

endif;

add_action( 'after_setup_theme', 'extendable_support' );

if ( ! function_exists( 'extendable_styles' ) ) :

	/**
	 * Enqueue styles.
	 *
	 * @since Extendable 1.0
	 *
	 * @return void
	 */
	function extendable_styles() {

		// Register theme stylesheet.
		// Cache-busting: usa o mtime do ficheiro para que, após cada deploy,
		// os navegadores (incl. mobile) descarreguem o CSS novo de imediato.
		$style_version = file_exists( get_stylesheet_directory() . '/style.css' )
			? filemtime( get_stylesheet_directory() . '/style.css' )
			: EXTENDABLE_THEME_VERSION;

		wp_register_style(
			'extendable-style',
			get_template_directory_uri() . '/style.css',
			array(),
			$style_version
		);

		// Enqueue theme stylesheet.
		wp_enqueue_style( 'extendable-style' );

		global $wp_version;
		if ( version_compare( $wp_version, '6.0.2', '<=' ) ) {
			// Register deprecate stylesheet.
			wp_register_style(
				'extendable-deprecate-style',
				get_template_directory_uri() . '/assets/css/deprecate-style.css',
				array(),
				EXTENDABLE_THEME_VERSION
			);
			// Enqueue deprecate stylesheet.
			wp_enqueue_style( 'extendable-deprecate-style' );
		}
	}

endif;

add_action( 'wp_enqueue_scripts', 'extendable_styles' );

/**
 * Enqueue block-specific styles.
 *
 * @since Extendable 2.0.11
 *
 * @return void
 */
function extendable_enqueue_block_styles() {
	// Check for specific blocks and enqueue their styles
	if ( has_block( 'contact-form-7/contact-form-selector' ) ) {
		wp_enqueue_style(
			'extendable-contact-form-7-style',
			get_template_directory_uri() . '/assets/css/contact-form-7.css',
			array(),
			EXTENDABLE_THEME_VERSION
		);
	}

	if ( has_block( 'wpforms/form-selector' ) ) {
		wp_enqueue_style(
			'extendable-wpforms-style',
			get_template_directory_uri() . '/assets/css/wpforms.css',
			array(),
			EXTENDABLE_THEME_VERSION
		);
	}
}

add_action( 'enqueue_block_assets', 'extendable_enqueue_block_styles' );

/**
 * Enqueue the World of Dreams carousel arrows script.
 *
 * @since Extendable 2.0.34
 *
 * @return void
 */
function extendable_enqueue_wod_carousel() {
	// Cache-busting: versão baseada no mtime do ficheiro JS.
	$carousel_version = file_exists( get_stylesheet_directory() . '/assets/js/wod-carousel.js' )
		? filemtime( get_stylesheet_directory() . '/assets/js/wod-carousel.js' )
		: EXTENDABLE_THEME_VERSION;

	wp_enqueue_script(
		'extendable-wod-carousel',
		get_template_directory_uri() . '/assets/js/wod-carousel.js',
		array(),
		$carousel_version,
		true
	);

	// Defer loading (WordPress 6.3+); harmless on older versions.
	wp_script_add_data( 'extendable-wod-carousel', 'strategy', 'defer' );
}
add_action( 'wp_enqueue_scripts', 'extendable_enqueue_wod_carousel' );

/**
 * Make the WooCommerce shop page permalink relative.
 *
 * Used by the empty-cart "Return to shop" button so it points to a relative
 * path (e.g. /loja/) instead of the absolute URL generated by WooCommerce.
 *
 * @since Extendable 2.5.0
 *
 * @param string $link The absolute shop page permalink.
 * @return string The relative permalink.
 */
function extendable_relative_shop_permalink( $link ) {
	return wp_make_link_relative( $link );
}
add_filter( 'woocommerce_get_shop_page_permalink', 'extendable_relative_shop_permalink' );

/**
 * Enqueue the AJAX add-to-cart + drawer script on the frontend.
 *
 * @since Extendable 2.5.0
 *
 * @return void
 */
function extendable_enqueue_add_to_cart_ajax() {
	wp_enqueue_script(
		'extendable-add-to-cart',
		get_template_directory_uri() . '/assets/js/wod-add-to-cart.js',
		array( 'jquery' ),
		EXTENDABLE_THEME_VERSION,
		true
	);
}
add_action( 'wp_enqueue_scripts', 'extendable_enqueue_add_to_cart_ajax' );

/**
 * Registers pattern categories.
 *
 * @since Extendable 1.0
 *
 * @return void
 */
function extendable_register_pattern_categories() {
	$block_pattern_categories = array(
		'header' => array( 'label' => __( 'Headers', 'extendable' ) ),
		'footer' => array( 'label' => __( 'Footers', 'extendable' ) ),
	);

	/**
	 * Filters the theme block pattern categories.
	 *
	 * @since Extendable 1.0
	 *
	 * @param array[] $block_pattern_categories {
	 *     An associative array of block pattern categories, keyed by category name.
	 *
	 *     @type array[] $properties {
	 *         An array of block category properties.
	 *
	 *         @type string $label A human-readable label for the pattern category.
	 *     }
	 * }
	 */
	$block_pattern_categories = apply_filters( 'extendable_block_pattern_categories', $block_pattern_categories );

	foreach ( $block_pattern_categories as $name => $properties ) {
		if ( ! WP_Block_Pattern_Categories_Registry::get_instance()->is_registered( $name ) ) {
			register_block_pattern_category( $name, $properties );
		}
	}
}
add_action( 'init', 'extendable_register_pattern_categories', 9 );

/**
 * Include animation functionality
 */
require_once get_template_directory() . '/inc/animations.php';

/**
 * Add primary-foreground duotone to extendify demo Site Logo block.
 * 
 * @param array $parsed_block Parsed block data.
 * @return array Filtered block data.
 */
function extendable_add_duotone_to_extendify_demo_site_logo( array $parsed_block ) : array {

	if ( 'core/site-logo' !== $parsed_block['blockName'] ) {
		return $parsed_block;
	}

	$logo_url = $parsed_block['attrs']['url'] ?? '';

	if ( '' === $logo_url ) {
		$logo_id  = (int) get_theme_mod( 'custom_logo' );
		$logo_url = $logo_id ? wp_get_attachment_url( $logo_id ) : '';
	}

	if ( '' === $logo_url ) {
		return $parsed_block;
	}

	$logo_file        = wp_basename( $logo_url );
	$allowed_prefixes = array( 'extendify-demo-', 'ext-custom-logo-' );

	$matches = false;
	foreach ( $allowed_prefixes as $prefix ) {
		if ( function_exists( 'str_starts_with' ) ) {
			$matches = str_starts_with( $logo_file, $prefix );
		} else {
			$matches = 0 === strpos( $logo_file, $prefix );
		}
		if ( $matches ) {
			break;
		}
	}

	if ( ! $matches ) {
		return $parsed_block;
	}

	$parsed_block['attrs']['style']['color']['duotone'] =
		'var:preset|duotone|primary-foreground';

	return $parsed_block;
}
add_filter( 'render_block_data', 'extendable_add_duotone_to_extendify_demo_site_logo', 10 );

/**
 * Exclude WooCommerce Templates from the Block Editor When WooCommerce Is Inactive
 *
 * @package Extendable
 * @since Extendable 2.0.21
 */

 function extendable_exclude_wc_block_templates( $templates, $query ) {
	if ( ! class_exists( 'WooCommerce' ) ) {
		$wc_template_slugs = array( 'checkout', 'single-product', 'archive-product' );
		foreach ( $templates as $key => $template ) {
			if ( isset( $template->slug ) && in_array( $template->slug, $wc_template_slugs, true ) ) {
				unset( $templates[ $key ] );
			}
		}
	}
	return $templates;
}
add_filter( 'get_block_templates', 'extendable_exclude_wc_block_templates', 10, 2 );

/**
 * Header helper.
 *
 * @package Extendable
 * @since Extendable 2.1.5
 */
function extendable_enqueue_header_scripts() {
	wp_enqueue_script(
		'extendable-header',
		get_template_directory_uri() . '/assets/js/header.js',
		array(),
		EXTENDABLE_THEME_VERSION,
		true
	);
}
add_action( 'wp_enqueue_scripts', 'extendable_enqueue_header_scripts' );

/**
 * Navigation customizations
 *
 * @package Extendable
 * @since Extendable 2.0.23
 */
if ( ! function_exists( 'extendable_enqueue_navigation_customizations' ) ) :
	/**
	 * Enqueue the JS that fetches logo & site title to customize the mobile navigation.
	 *
	 */
	function extendable_enqueue_navigation_customizations() {

		$logo_id   = get_theme_mod( 'custom_logo' );
    	$logo_url  = $logo_id ? wp_get_attachment_image_url( $logo_id, 'full' ) : '';
    	$site_title = get_bloginfo( 'name' );

		wp_enqueue_script(
			'extendable-navigation_customizations',
			get_template_directory_uri() . '/assets/js/navigation-customization.js',
			array(),   // no dependencies; add 'wp-interactivity' if you switch back to that version
			null,
			true        // load in footer
		);

		wp_localize_script( 'extendable-navigation_customizations', 'ExtendableNavData',
			array(
        		'logoUrl'   => $logo_url,
        		'siteTitle' => $site_title,
    		)
		);
	}
endif;
add_action( 'wp_enqueue_scripts', 'extendable_enqueue_navigation_customizations' );

/**
 * Set default template for new pages in the block editor (auto-drafts)
 *
 * @since Extendable 2.0.26
 * @return void
 */
function extendable_set_default_template_for_auto_drafts( WP_REST_Response $response, WP_Post $post ) {

	if ( 'page' !== $post->post_type ) {
		return $response;
	}
	
	if ( 'auto-draft' !== $post->post_status ) {
		return $response;
	}

	$current_template = isset( $response->data['template'] ) ? $response->data['template'] : '';

	if ( ! empty( $current_template ) && 'page' !== $current_template ) {
		return $response;
	}

	$response->data['template'] = 'page-with-title';

	return $response;
}
add_filter( 'rest_prepare_page', 'extendable_set_default_template_for_auto_drafts', 10, 2 );
 
/**
 * Set default template for new pages when saved/published
 *
 * @since Extendable 2.0.28
 * @param int     $post_id Post ID.
 * @param WP_Post $post    Post object.
 * @param bool    $update  Whether this is an existing post being updated.
 * @return void
 */
function extendable_set_default_template_for_new_pages( $post_id, $post, $update ) {

	if ( 'page' !== $post->post_type ) {
		return;
	}

	if ( $update ) {
		return;
	}

	if ( 'revision' === $post->post_status ) {
		return;
	}

	$current_template = get_page_template_slug( $post_id );
    
	// If no template is set or it's the default template, set our default
	if ( empty( $current_template ) || 'page' === $current_template ) {
		update_post_meta( $post_id, '_wp_page_template', 'page-with-title' );
	}
}
add_action( 'wp_insert_post', 'extendable_set_default_template_for_new_pages', 10, 3 );

/**
 * Hide block style variations from editor UI while keeping them registered
 */
function extendable_hide_block_style_variations() {
	$css = '
		.block-editor-block-styles__item[aria-label*="Brutalism 1"],
		.block-editor-block-styles__item[aria-label*="Organic 1"],
		.block-editor-block-styles__item[aria-label*="Soft 1"],
		.block-editor-block-styles__item[aria-label*="Gradient 1"],
		.block-editor-block-styles__item[aria-label*="Matrix 1"],
		.block-editor-block-styles__item[aria-label*="Prism 1"],
		.block-editor-block-styles__item[aria-label*="Wave 1"] {
			display: none !important;
		}
	';
	
	wp_add_inline_style('wp-edit-blocks', $css);
}
add_action( 'enqueue_block_editor_assets', 'extendable_hide_block_style_variations' );

/**
 * Hide block style variations from site editor style panel
 */
function extendable_hide_site_editor_block_style_variations() {
	$css = '
		/* Hide specific design aesthetic variations in site editor */
		.components-navigator-button[id*="brutalism-1--"],
		.components-navigator-button[id*="organic-1--"],
		.components-navigator-button[id*="soft-1--"],
		.components-navigator-button[id*="gradient-1--"],
		.components-navigator-button[id*="matrix-1--"],
		.components-navigator-button[id*="prism-1--"],
		.components-navigator-button[id*="wave-1--"] {
			display: none !important;
		}
		
		/* Hide the Style Variations heading if all variations are hidden */
		.components-h-stack:has(.components-navigator-button[id*="ext-preset--"]:not([style*="display: none"])) .edit-site-global-styles-subtitle:contains("Style Variations") {
			display: none !important;
		}
		
		/* Alternative approach - hide the entire Style Variations section */
		.edit-site-global-styles-subtitle:contains("Style Variations") + .components-item-group {
			display: none !important;
		}
		
		.edit-site-global-styles-subtitle:contains("Style Variations") {
			display: none !important;
		}
	';
	
	wp_add_inline_style('wp-edit-site', $css);
}
add_action( 'admin_enqueue_scripts', 'extendable_hide_site_editor_block_style_variations' );

// Temporary fix: Hide matrix-1, prism-1, wave-1 variations when Extendify < 2.4.0
function extendable_filter_global_styles_rest_response( $response, $handler, $request ) {
	$route = $request->get_route();
	if ( strpos( $route, '/wp/v2/global-styles/themes/' ) === false ) {
		return $response;
	}

	if ( ! function_exists( 'get_plugins' ) ) {
		require_once ABSPATH . 'wp-admin/includes/plugin.php';
	}

	$plugins       = get_plugins();
	$should_filter = false;

	foreach ( $plugins as $plugin_file => $plugin_data ) {
		if ( 'extendify-local' === $plugin_data['TextDomain'] && is_plugin_active( $plugin_file ) ) {
			if ( version_compare( $plugin_data['Version'], '2.4.0', '<' ) ) {
				$should_filter = true;
			}
			break;
		}
	}

	if ( ! $should_filter ) {
		return $response;
	}

	$patterns = array( 'matrix-1', 'prism-1', 'wave-1' );
	$data     = $response->get_data();

	if ( isset( $data['styles']['blocks'] ) && is_array( $data['styles']['blocks'] ) ) {
		foreach ( $data['styles']['blocks'] as $block_name => $block_data ) {
			if ( isset( $block_data['variations'] ) && is_array( $block_data['variations'] ) ) {
				foreach ( $block_data['variations'] as $variation_slug => $variation_data ) {
					foreach ( $patterns as $pattern ) {
						if ( strpos( $variation_slug, $pattern ) !== false ) {
							unset( $data['styles']['blocks'][ $block_name ]['variations'][ $variation_slug ] );
							break;
						}
					}
				}
				if ( empty( $data['styles']['blocks'][ $block_name ]['variations'] ) ) {
					unset( $data['styles']['blocks'][ $block_name ]['variations'] );
				}
			}
		}
	}

	if ( isset( $data['_links']['wp:block-style-variations'] ) ) {
		$data['_links']['wp:block-style-variations'] = array_filter(
			$data['_links']['wp:block-style-variations'],
			function( $variation ) use ( $patterns ) {
				$href = $variation['href'] ?? '';
				foreach ( $patterns as $pattern ) {
					if ( strpos( $href, $pattern ) !== false ) {
						return false;
					}
				}
				return true;
			}
		);
		$data['_links']['wp:block-style-variations'] = array_values( $data['_links']['wp:block-style-variations'] );
	}

	$response->set_data( $data );
	return $response;
}
add_filter( 'rest_post_dispatch', 'extendable_filter_global_styles_rest_response', 10, 3 );

/**
 * Catalog buttons: use "VER PRODUTO" for variable products.
 *
 * @since Extendable 2.5.0
 */
add_filter( 'woocommerce_product_add_to_cart_text', 'extendable_add_to_cart_text', 99, 2 );
function extendable_add_to_cart_text( $text, $product ) {
	return __( 'VER PRODUTO', 'woocommerce' );
}

/**
 * One-time auto-tagging of products by keyword.
 *
 * Runs only once, guarded by the `wod_tags_synced_v3` option.
 *
 * @since Extendable 2.5.0
 */
function extendable_sync_product_tags_v3() {
	if ( get_option( 'wod_tags_synced_v3' ) ) {
		return;
	}

	$mapping = array(
		'Tugalândia'   => 'Tugalândia',
		'Hippie Ibiza' => 'Hippie Ibiza',
		'Zucalatina'   => 'Zucalatina',
		'Electronic'   => 'Electronic',
		'Jonny D'      => 'Jonny D',
	);

	$product_ids = get_posts(
		array(
			'post_type'   => 'product',
			'post_status' => 'publish',
			'numberposts' => -1,
			'fields'      => 'ids',
		)
	);

	foreach ( $product_ids as $product_id ) {
		$title = get_the_title( $product_id );
		$tags  = array();

		foreach ( $mapping as $keyword => $tag ) {
			if ( false !== stripos( $title, $keyword ) ) {
				$tags[] = $tag;
			}
		}

		if ( ! empty( $tags ) ) {
			wp_set_object_terms( $product_id, $tags, 'product_tag', true );
		}
	}

	update_option( 'wod_tags_synced_v3', true );
}
add_action( 'init', 'extendable_sync_product_tags_v3' );

/**
 * One-time auto-assignment of product brands (product_brand) by keyword.
 *
 * Runs only once, guarded by the `wod_brands_synced_v1` option.
 *
 * @since Extendable 2.5.0
 */
function extendable_sync_product_brands() {
	if ( get_option( 'wod_brands_synced_v1' ) ) {
		return;
	}

	// Aguardar que a taxonomia de marca (product_brand) esteja registada.
	if ( ! taxonomy_exists( 'product_brand' ) ) {
		return;
	}

	$mapping = array(
		'Dreams Of' => 'Dreams Of',
		'JONNY D'   => 'Jonny D',
	);

	$product_ids = get_posts(
		array(
			'post_type'   => 'product',
			'post_status' => 'publish',
			'numberposts' => -1,
			'fields'      => 'ids',
		)
	);

	foreach ( $product_ids as $product_id ) {
		$title  = get_the_title( $product_id );
		$brands = array();

		foreach ( $mapping as $keyword => $brand ) {
			if ( false !== stripos( $title, $keyword ) ) {
				$brands[] = $brand;
			}
		}

		if ( ! empty( $brands ) ) {
			wp_set_object_terms( $product_id, $brands, 'product_brand', true );
		}
	}

	update_option( 'wod_brands_synced_v1', true );
}
add_action( 'init', 'extendable_sync_product_brands', 20 );

/**
 * Public REST endpoint for real-time price sync.
 *
 * GET /wp-json/wod/v1/prices
 *
 * @since Extendable 2.5.0
 */
function extendable_register_prices_route() {
	register_rest_route(
		'wod/v1',
		'/prices',
		array(
			'methods'             => 'GET',
			'callback'            => 'extendable_prices_callback',
			'permission_callback' => '__return_true',
		)
	);
}
add_action( 'rest_api_init', 'extendable_register_prices_route' );

function extendable_prices_callback() {
	$products = get_posts(
		array(
			'post_type'   => 'product',
			'post_status' => 'publish',
			'numberposts' => -1,
		)
	);

	$data = array();

	foreach ( $products as $post ) {
		$product = wc_get_product( $post );
		if ( ! $product ) {
			continue;
		}

		$data[] = array(
			'slug'          => $product->get_slug(),
			'sku'           => $product->get_sku(),
			'regular_price' => $product->get_regular_price(),
			'sale_price'    => $product->get_sale_price(),
			'price'         => $product->get_price(),
			'stock_status'  => $product->get_stock_status(),
		);
	}

	$response = new WP_REST_Response( $data, 200 );
	$response->header( 'Access-Control-Allow-Origin', '*' );

	return $response;
}

/**
 * Bypass total de cache (servidor / CDN) nas páginas públicas.
 *
 * Envia cabeçalhos estritos de no-cache para visitantes (não admin),
 * garantindo visualização em tempo real após cada deploy.
 *
 * @since Extendable 2.5.0
 */
function extendable_send_no_cache_headers() {
	if ( is_admin() ) {
		return;
	}

	header( 'Cache-Control: no-store, no-cache, must-revalidate, max-age=0' );
	header( 'Pragma: no-cache' );
	header( 'Expires: Wed, 11 Jan 1984 05:00:00 GMT' );
}
add_action( 'send_headers', 'extendable_send_no_cache_headers' );

/**
 * Desativa forçadamente o "Coming Soon" do WooCommerce.
 *
 * @since Extendable 2.5.0
 */
add_filter( 'woocommerce_coming_soon_exclude', '__return_true' );

function extendable_force_woocommerce_live() {
	if ( 'no' !== get_option( 'woocommerce_coming_soon' ) ) {
		update_option( 'woocommerce_coming_soon', 'no' );
	}
	if ( 'no' !== get_option( 'woocommerce_store_pages_only' ) ) {
		update_option( 'woocommerce_store_pages_only', 'no' );
	}
}
add_action( 'init', 'extendable_force_woocommerce_live' );

/**
 * One-time stock fix: T-Shirts Jonny D (243 preto, 244 branco) em 'instock'
 * com todas as variações disponíveis.
 *
 * @since Extendable 2.5.0
 */
function extendable_sync_jonny_d_stock() {
	if ( get_option( 'wod_jonnyd_stock_synced_v1' ) ) {
		return;
	}
	if ( ! function_exists( 'wc_get_product' ) ) {
		return;
	}

	$product_ids = array( 243, 244 );

	foreach ( $product_ids as $product_id ) {
		$product = wc_get_product( $product_id );
		if ( ! $product ) {
			continue;
		}

		$product->set_stock_status( 'instock' );
		$product->save();

		if ( $product->is_type( 'variable' ) ) {
			foreach ( $product->get_children() as $variation_id ) {
				$variation = wc_get_product( $variation_id );
				if ( ! $variation ) {
					continue;
				}

				$variation->set_manage_stock( false );
				$variation->set_stock_status( 'instock' );
				$variation->save();
			}
		}
	}

	update_option( 'wod_jonnyd_stock_synced_v1', true );
}
add_action( 'init', 'extendable_sync_jonny_d_stock', 20 );

/**
 * One-time price fix: define 20,00 € nas T-Shirts Jonny D (243 preto,
 * 244 branco) e respetivas variações. Sem preço, o WooCommerce marca
 * is_purchasable() como false e esconde as variações no front-end.
 *
 * @since Extendable 2.5.0
 */
function extendable_sync_jonny_d_prices() {
	if ( get_option( 'wod_jonnyd_prices_synced_v2' ) ) {
		return;
	}
	if ( ! function_exists( 'wc_get_product' ) ) {
		return;
	}

	$price = '20';

	// IDs hardcoded para máxima robustez: produtos pai + respetivas variações.
	$ids = array( 243, 244, 255, 256, 257, 258, 261, 262, 263, 264 );

	foreach ( $ids as $id ) {
		update_post_meta( $id, '_regular_price', $price );
		update_post_meta( $id, '_price', $price );
	}

	// Recalcula a disponibilidade e a gama de preços dos produtos pai.
	wc_delete_product_transients( 243 );
	wc_delete_product_transients( 244 );

	update_option( 'wod_jonnyd_prices_synced_v2', true );
}
add_action( 'init', 'extendable_sync_jonny_d_prices', 25 );

/**
 * Injeta a camada fixa de fundo #fixed-stage-bg no início do <body>.
 *
 * @since Extendable 2.5.0
 */
function extendable_stage_bg_markup() {
	echo '<div id="fixed-stage-bg" aria-hidden="true"></div>';
}
add_action( 'wp_body_open', 'extendable_stage_bg_markup' );

/**
 * Injeta dinamicamente a imagem de fundo da página ativa no #fixed-stage-bg.
 *
 * - Categoria de produto (is_product_category) com imagem (thumbnail_id)
 *   → usa essa imagem.
 * - Sem imagem na categoria, ou página inicial (is_front_page) → usa a
 *   imagem padrão Terra/Espaço da home.
 *
 * @since Extendable 2.5.0
 */
function extendable_inject_stage_bg_css() {
	$bg_url = '';

	if ( is_product_category() ) {
		$term_id  = get_queried_object_id();
		$thumb_id = get_term_meta( $term_id, 'thumbnail_id', true );
		if ( $thumb_id ) {
			$bg_url = wp_get_attachment_url( $thumb_id );
		}
	}

	if ( empty( $bg_url ) ) {
		// Padrão: Terra/Espaço (da home).
		$bg_url = apply_filters(
			'wod_default_stage_bg',
			'https://shop.worldofdreams.pt/wp-content/uploads/2026/10/foto-terra-home-final-comprimida.webp'
		);
	}

	if ( $bg_url ) {
		printf(
			'<style id="wod-stage-bg-inline">#fixed-stage-bg{background-image:url(%s) !important;}</style>',
			esc_url( $bg_url )
		);
	}
}
add_action( 'wp_head', 'extendable_inject_stage_bg_css' );
